"""HTML report generator for the AI SAST Scanner."""
import os
from dataclasses import asdict
from html import escape


def generate_html(summary: dict, findings: list, output_path: str):
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    sev_colors = {
        "CRITICAL": "#ff3b30",
        "HIGH": "#ff9500",
        "MEDIUM": "#ffcc00",
        "LOW": "#34c759",
    }

    rows = []
    for i, f in enumerate(sorted(findings, key=lambda x: -x.risk_score)):
        color = sev_colors.get(f.severity, "#888")
        rows.append(f"""
        <div class="finding" data-severity="{f.severity}">
          <div class="fhead" onclick="toggleFinding({i})">
            <span class="sev" style="background:{color}">{f.severity}</span>
            <span class="fname">{escape(f.name)}</span>
            <span class="score">risk {f.risk_score}</span>
            <span class="chev">▶</span>
          </div>
          <div class="fbody" id="fbody-{i}">
            <div class="row"><b>File:</b> <code>{escape(f.file)}:{f.line}</code></div>
            <div class="row"><b>CWE:</b> {f.cwe} &nbsp; <b>OWASP:</b> {f.owasp}</div>
            <div class="row"><b>Confidence:</b> {f.confidence} &nbsp; <b>Fingerprint:</b> <code>{f.fingerprint}</code></div>
            <pre class="code">{escape(f.code_snippet)}</pre>
            <div class="row"><b>Remediation:</b> {escape(f.remediation)}</div>
            <pre class="fix">{escape(f.example_fix)}</pre>
          </div>
        </div>
        """)

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>AI SAST Scanner Report</title>
<style>
  body{{font-family:'SF Mono','Menlo',monospace;background:#0b0e14;color:#d5d9e0;margin:0;padding:24px}}
  h1{{color:#7dd3fc;margin:0 0 8px}}
  .subtitle{{color:#94a3b8;margin-bottom:24px}}
  .stats{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin-bottom:28px}}
  .stat{{background:#111827;border:1px solid #1f2937;border-radius:10px;padding:16px}}
  .stat .n{{font-size:28px;font-weight:700;color:#f1f5f9}}
  .stat .l{{font-size:12px;color:#94a3b8;text-transform:uppercase;letter-spacing:0.5px}}
  .finding{{background:#111827;border:1px solid #1f2937;border-radius:10px;margin-bottom:12px;overflow:hidden}}
  .fhead{{padding:14px 18px;display:flex;align-items:center;gap:12px;cursor:pointer;user-select:none}}
  .fhead:hover{{background:#1a2233}}
  .sev{{color:#000;font-weight:800;font-size:11px;padding:3px 10px;border-radius:20px}}
  .fname{{flex:1;color:#e5e7eb;font-weight:600}}
  .score{{color:#94a3b8;font-size:12px}}
  .chev{{color:#64748b;transition:transform 0.2s}}
  .fbody{{display:none;padding:0 18px 18px;border-top:1px solid #1f2937}}
  .fbody.open{{display:block}}
  .row{{margin:10px 0;font-size:13px}}
  code{{background:#0b0e14;padding:2px 6px;border-radius:4px;color:#fbbf24}}
  pre.code{{background:#0b0e14;padding:12px;border-radius:6px;border-left:3px solid #ff3b30;overflow-x:auto;color:#f87171;font-size:12px}}
  pre.fix{{background:#022c22;padding:12px;border-radius:6px;border-left:3px solid #34c759;overflow-x:auto;color:#86efac;font-size:12px}}
  .footer{{margin-top:32px;color:#475569;font-size:11px;text-align:center}}
</style>
</head>
<body>
  <h1>⚡ AI SAST Scanner Report</h1>
  <div class="subtitle">Scanned {summary['scanned_at']} · {summary['files_scanned']} files · {summary['lines_scanned']} LoC</div>

  <div class="stats">
    <div class="stat"><div class="n">{summary['total_findings']}</div><div class="l">Total Findings</div></div>
    <div class="stat"><div class="n" style="color:#ff3b30">{summary['by_severity'].get('CRITICAL',0)}</div><div class="l">Critical</div></div>
    <div class="stat"><div class="n" style="color:#ff9500">{summary['by_severity'].get('HIGH',0)}</div><div class="l">High</div></div>
    <div class="stat"><div class="n" style="color:#ffcc00">{summary['by_severity'].get('MEDIUM',0)}</div><div class="l">Medium</div></div>
    <div class="stat"><div class="n" style="color:#34c759">{summary['by_severity'].get('LOW',0)}</div><div class="l">Low</div></div>
  </div>

  {''.join(rows)}

  <div class="footer">Generated by AI SAST Scanner · github.com/CyberEnthusiastic</div>

<script>
function toggleFinding(i){{
  const b = document.getElementById('fbody-'+i);
  b.classList.toggle('open');
}}
</script>
</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as fp:
        fp.write(html)
